[package]
name = "smwe-emu"
version = "0.1.0"
edition = "2021"
authors = ["Selicre"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wdc65816 = { path = "../wdc65816" }
