[package]
name = "nsmwe_rom"
version = "0.1.0"
authors = ["Adam GÄ…sior (Adanos020)"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.1"
num_enum = "0.5.1"