[package]
name = "smwe-project"
version = "0.1.0"
authors = ["Adam GÄ…sior (Adanos020)", "Raven Szewczyk (eigenraven)"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smwe-rom = { path = "../smwe-rom" }
